spring:
  application:
    name: cotacao
  datasource:
    url: jdbc:mysql://localhost:3306/desenvolvimento?useTimeZone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update